dubbo:
  cloud:
    # Dubbo 消费端订阅服务端的应用名，多个服务提供者用逗号分隔
    # 这里订阅"自己"，会被忽略掉，请根据实际情况添加
    subscribed-services: gportal,user-service-provider
    # dubbo 协议
  protocol:
    id: dubbo
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  scan:
    base-packages: com.wjw.cloud.gportal
server:
  port: 8080
spring:
  application:
    name: gportal
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: 192.168.8.133:8848
        username: nacos
