dubbo:
  cloud:
    # Dubbo 消费端订阅服务端的应用名，多个服务提供者用逗号分隔
    # 这里订阅"自己"，会被忽略掉，请根据实际情况添加
    subscribed-services: gportal,user-service,shop-service
    # dubbo 协议
  protocol:
    id: dubbo
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  scan:
    base-packages: com.wjw.cloud.user
#server:
#  port: 8080
spring:
  application:
    name: user-service
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/colud-2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 30
      max-active: 100
      min-idle: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: 127.0.0.1:8848
        username: nacos
    alibaba:
      seata:
        # seata 服务分组，要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
        tx-service-group: my_test_tx_group

seata:
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      cluster:
        server-addr: 127.0.0.1:8848
        group: SEATA_GROUP
        username: nacos
        password: nacos
        application: seata-server

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    mapper-locations: classpath*:mapper/**/*:Mapper:xml