dubbo:
  application:
    name: biz-service
  registrt:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
  protocol:
    name: dubbo
    port: -1
    token: true
#dubbo:
#  cloud:
#    subscribed-services: biz-service
#  protocol:
#    id: dubbo
#    name: dubbo
#    port: -1
#  scan:
#    base-packages: com.wjw.duboo.bizservice
#spring:
#  application:
#    name: biz-service
#server:
#  port: 8080
#  cloud:
#    nacos:
#      discovery:
#        namespace: public
#        password: nacos
#        server-addr: 127.0.0.1:8848
#        username: nacos